version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: welcome_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: welcome_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: welcome_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: welcome_db
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: welcome_frontend
    ports:
      - "3000:3000"
    restart: unless-stopped